# config.toml

[paths]
#paths are relative to executable directory
output_directory = "frames"

[rendering_main]
texture_width = 3800
texture_height = 1080

# Please don't change these
texture_samples = 1
arc_resolution = 25

[main_window]
# The size of the monitoring window.
# Currently scaling to 1/2 of texture resolution
width = 1900
height = 540

[input_window]
# The size of the input window.
# Currently scaling to 1/2 of texture resolution
width = 600
height = 400

[osc]
# OSC listening port. UDP only.
rx_port = 8000

[frame_recorder]
# Settings for the frame recorder
# Frame limit of 30000 frames is about 16m40s at 30fps
# Frame limit of 50000 frames is about 13m53s at 60fps
frame_limit = 50000
fps = 30

[speed]
bpm = 120
